ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS full_name_bn text,
  ADD COLUMN IF NOT EXISTS photo_url text,
  ADD COLUMN IF NOT EXISTS birth_certificate_no text,
  ADD COLUMN IF NOT EXISTS blood_group text,
  ADD COLUMN IF NOT EXISTS nationality text,
  ADD COLUMN IF NOT EXISTS religion text,
  ADD COLUMN IF NOT EXISTS present_village text,
  ADD COLUMN IF NOT EXISTS present_po text,
  ADD COLUMN IF NOT EXISTS present_upazila text,
  ADD COLUMN IF NOT EXISTS present_district text,
  ADD COLUMN IF NOT EXISTS permanent_village text,
  ADD COLUMN IF NOT EXISTS permanent_po text,
  ADD COLUMN IF NOT EXISTS permanent_upazila text,
  ADD COLUMN IF NOT EXISTS permanent_district text,
  ADD COLUMN IF NOT EXISTS father_name text,
  ADD COLUMN IF NOT EXISTS father_profession text,
  ADD COLUMN IF NOT EXISTS father_mobile text,
  ADD COLUMN IF NOT EXISTS father_nid text,
  ADD COLUMN IF NOT EXISTS mother_name text,
  ADD COLUMN IF NOT EXISTS mother_profession text,
  ADD COLUMN IF NOT EXISTS mother_mobile text,
  ADD COLUMN IF NOT EXISTS mother_nid text,
  ADD COLUMN IF NOT EXISTS annual_family_income numeric,
  ADD COLUMN IF NOT EXISTS local_guardian_name text,
  ADD COLUMN IF NOT EXISTS local_guardian_relation text,
  ADD COLUMN IF NOT EXISTS local_guardian_mobile text,
  ADD COLUMN IF NOT EXISTS previous_school_name text,
  ADD COLUMN IF NOT EXISTS previous_school_address text,
  ADD COLUMN IF NOT EXISTS last_class_passed text,
  ADD COLUMN IF NOT EXISTS tc_no text,
  ADD COLUMN IF NOT EXISTS board_roll_no text,
  ADD COLUMN IF NOT EXISTS board_reg_no text,
  ADD COLUMN IF NOT EXISTS last_exam_result text,
  ADD COLUMN IF NOT EXISTS section text,
  ADD COLUMN IF NOT EXISTS residential_status text,
  ADD COLUMN IF NOT EXISTS academic_year text,
  ADD COLUMN IF NOT EXISTS admission_exam_score text,
  ADD COLUMN IF NOT EXISTS disease_disability text,
  ADD COLUMN IF NOT EXISTS allergies text,
  ADD COLUMN IF NOT EXISTS emergency_contact_name text,
  ADD COLUMN IF NOT EXISTS emergency_contact_mobile text,
  ADD COLUMN IF NOT EXISTS birth_certificate_url text,
  ADD COLUMN IF NOT EXISTS tc_url text,
  ADD COLUMN IF NOT EXISTS marksheet_url text,
  ADD COLUMN IF NOT EXISTS guardian_nid_url text;

ALTER TABLE public.teachers
  ADD COLUMN IF NOT EXISTS photo_url text,
  ADD COLUMN IF NOT EXISTS father_husband_name text,
  ADD COLUMN IF NOT EXISTS mother_name text,
  ADD COLUMN IF NOT EXISTS national_id text,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS religion text,
  ADD COLUMN IF NOT EXISTS blood_group text,
  ADD COLUMN IF NOT EXISTS present_address text,
  ADD COLUMN IF NOT EXISTS permanent_address text,
  ADD COLUMN IF NOT EXISTS qualifications jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS madrasa_certificates text,
  ADD COLUMN IF NOT EXISTS bed_med text,
  ADD COLUMN IF NOT EXISTS special_training text,
  ADD COLUMN IF NOT EXISTS applied_post text,
  ADD COLUMN IF NOT EXISTS total_experience_years numeric,
  ADD COLUMN IF NOT EXISTS previous_jobs jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS expected_salary numeric,
  ADD COLUMN IF NOT EXISTS employment_type text,
  ADD COLUMN IF NOT EXISTS reference_contacts jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bank_account_no text,
  ADD COLUMN IF NOT EXISTS bank_name text,
  ADD COLUMN IF NOT EXISTS bank_branch text,
  ADD COLUMN IF NOT EXISTS routing_no text,
  ADD COLUMN IF NOT EXISTS mobile_banking_no text,
  ADD COLUMN IF NOT EXISTS tin text,
  ADD COLUMN IF NOT EXISTS physically_fit boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS no_criminal_record boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nid_scan_url text,
  ADD COLUMN IF NOT EXISTS education_certificate_urls text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS experience_certificate_url text,
  ADD COLUMN IF NOT EXISTS police_clearance_url text,
  ADD COLUMN IF NOT EXISTS cv_url text,
  ADD COLUMN IF NOT EXISTS department text,
  ADD COLUMN IF NOT EXISTS class_assigned text,
  ADD COLUMN IF NOT EXISTS probation_period text;